apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  # replicas: {{.Values.replicaCount}}
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      namespace: helloworld
      labels:
        app: "helloworld"
    spec:
      containers:
      - image: nginx:1.11.4
        name: nginx
        ports:
        - containerPort: 80
        command:
        - /bin/bash
        - -c
        - 'echo "<h1>{{.Values.message}}</h1>" > /usr/share/nginx/html/index.html; /usr/sbin/nginx -g "daemon off;"'
