apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 30080
    targetPort: 80
  selector:
    app: helloworld
  externalIPs:
  - 10.0.10.10
